server:
  port: 8090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:

            - id: merchant-service
              uri: lb://MERCHANT-ONBOARDING
              predicates:
                - Path=/merchant/**
              filters:
                - StripPrefix=1

            - id: document-service
              uri: lb://DOCUMENT-SERVICE
              predicates:
                - Path=/documents/**
              filters:
                - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
